### ISSUE TITLE
Help with reading TIFF file

### ISSUE THREAD

**Issue by eturkes** [niaid/sitk-ibex#37]
Hello there. I want to try out your software on some of my data but I'm having trouble at the initial registration step. Running into a couple issues. To start, I am not able to supply the channel name, I get this error `Exception: Channel name "DAPI" is not in filename marker list: []`. I looked into it and `io.py` seems to expect a `ome_info.channel_names` field, but this is not present in my metadata when I open my TIFF in ImageJ. I do however have information in the name fields of my channels in the OME XML, it seems this is not parsed by your software though?

I also tried using a variety of integers, Ch1, etc, when I do that I get this error `TypeError: VectorIndexSelectionCastImageFilter.__init__() takes 1 positional argument but 3 were given`.

Finally, I tried not supplying a channel. The software does say reading whole file, but now I get the error `sitk::ERROR: Filter does not support casting from casting vector of 8-bit unsigned integer to 32-bit float`.

The images I'm using are originally .czi format. I've tried converting it into a TIFF in both ZEN and QuPath. Have not looked extensively into ImageJ however, as it opens up my image as a set of 4 series for some reason. I don't really know why or what this means. I'm a bit of a novice in image processing, so if you can help point me in the right direction I can try exporting in ImageJ or do whatever else that might get this working.

Looking forward to hearing from you!

**Comment by blowekamp** [comment]
Thank you for reporting your issues. The `VectorIndexSelectionCastImageFilter` error was due to a problem in the code. It has been addressed and [`v0.4` tagged and packaged](https://github.com/niaid/sitk-ibex/releases/tag/v0.4). Please update or re-download the package and try again.

**Comment by eturkes** [comment]
Thank you for the prompt fix! The code does indeed run from start to finish now, though I am still not getting usable output. I'll try to summarize my troubleshooting in another issue.
